<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="finger_len" value="0.05" />
  <xacro:property name="finger_width" value="0.01" />
  <xacro:property name="finger_thick" value="0.01" />

  <!-- Gripper base link attached to the arm's end-effector -->
  <link name="gripper_base_link">
    <visual>
      <geometry>
        <box size="0.03 0.04 0.03" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.04 0.03" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- Joint to attach gripper to arm end-effector -->
  <joint name="gripper_joint" type="fixed">
    <parent link="link3"/> <!-- Attached to the last link of the arm -->
    <child link="gripper_base_link"/>
    <origin xyz="0 0 0.04" rpy="0 0 0"/> <!-- Offset from link3 -->
  </joint>

  <!-- Left Gripper Finger -->
  <link name="left_finger_link">
    <visual>
      <origin xyz="0 0 ${-finger_len/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${finger_thick} ${finger_width} ${finger_len}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${-finger_len/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${finger_thick} ${finger_width} ${finger_len}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${-finger_len/2}" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="left_finger_joint" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="left_finger_link"/>
    <origin xyz="0 0.02 -0.02" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="0.02" effort="10" velocity="0.1"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Right Gripper Finger -->
  <link name="right_finger_link">
    <visual>
      <origin xyz="0 0 ${-finger_len/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${finger_thick} ${finger_width} ${finger_len}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${-finger_len/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${finger_thick} ${finger_width} ${finger_len}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${-finger_len/2}" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="right_finger_joint" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="right_finger_link"/>
    <origin xyz="0 -0.02 -0.02" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit lower="0" upper="0.02" effort="10" velocity="0.1"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Transmissions for gripper joints -->
  <transmission name="left_finger_transmission">
    <type>actuator_transmission/SimpleTransmission</type>
    <joint name="left_finger_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_finger_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_finger_transmission">
    <type>actuator_transmission/SimpleTransmission</type>
    <joint name="right_finger_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_finger_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <gazebo reference="gripper_base_link">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="left_finger_link">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="right_finger_link">
    <material>Gazebo/Red</material>
  </gazebo>

</robot>
